server:
  port: 8081
  gateway:
    port: 5684

spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  jpa:
    show-sql: true
    properties:
      javax:
        cache:
          missing_cache_strategy: create
        persistence:
          sharedCache: 
            mode: ENABLE_SELECTIVE
      hibernate:
        ddl-auto: create
        format_sql: true
        generate_statistics: false
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory  
          
logging:
  level:
    org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl: ERROR
    com:
      thyng: trace
      hazelcast: info